version: '2'
services:
  minio:
    image: quay.io/minio/minio
    networks:
      - airflow
    command: server /data --console-address ":9001"
    ports:
      - 9000:9000
      - 9001:9001
    restart: always      
  sqlite-web:
    image: fletchjeffastro/astro_sdk_workshop:0.0.2
    networks:
      - airflow
    command: sqlite_web -p 8088 -H 0.0.0.0 /data/astro_orders.db
    ports:
      - 8088:8088
    restart: always
    volumes:
      - ${PWD}/include:/data   
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"
