version: '2'
services:
  pgadmin:
    image: dpage/pgadmin4
    networks:
      - airflow
    ports:
      - 5050:80
    environment:
    - PGADMIN_DEFAULT_EMAIL=name@example.com
    - PGADMIN_DEFAULT_PASSWORD=admin
    extra_hosts:
      - "host.docker.internal:host-gateway"      
  scheduler:
    extra_hosts:
      - "host.docker.internal:host-gateway"  
  webserver:
    extra_hosts:
      - "host.docker.internal:host-gateway"
  triggerer:
    extra_hosts:
      - "host.docker.internal:host-gateway"    